name: Daily run
on: workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    name: Run and save artifacts
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
      - uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore